### ISSUE TITLE
Add missing installation step

### ISSUE THREAD

**Issue by madskjeldgaard** [jamesb93/ReaCoMa#3]
Hi! Thanks for the great work on this. These scripts are fantastic!
There's a step missing in the installation process described (for newbies of Reaper for example): How do you load the scripts after download? (actions->new action->choose scripts).
Best

**Comment by jamesb93** [comment]
Hey Mads,

I think I've seen you around in FluCoMa discourse 👍 

I used to have this in the README but i removed it because actually, would you believe, I got lots of complaints that it's not the right way to do it. I do talk about it in the video tutorial series, but obviously it would be much more immediate if people read it here.

My preferred way is to just do the `Run ReaScript EEL/Lua` action. Since you brought up the issue, what do you think the most beginner friendly way is to run the scripts?

Thanks for raising an issue by the way.
